name: Flutter CI

on:
  pull_request:
    branches: [dev, main]


jobs:
  build:
    name: Build and Analyze
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze code
        run: flutter analyze

      - name: Check Android build
        run: flutter build apk --debug

      - name: Check iOS build
        run: flutter build ios --no-codesign
